---
title: "Research"
---

For complete and always updated works, incl. preprints, please click [here](https://scholar.google.com/citations?user=UFsfJkAAAAAJ&hl=en)

### 2024

**Slabowska AO**, Pyke C, Hvid H, **Jessen LE**, Baumgart S, Das V. A systematic evaluation of state-of-the-art deconvolution methods in spatial transcriptomics: insights from cardiovascular disease and chronic kidney disease. *Front Bioinform.* 2024 Mar 27;4:1352594. doi: 10.3389/fbinf.2024.1352594. PMID: 38601476; PMCID: PMC11004278.

### 2023

**Montemurro A**, **Povlsen HR**, **Jessen LE**, Nielsen M. Benchmarking data-driven filtering for denoising of TCRpMHC single-cell data. *Sci Rep*. 2023 Sep 26;13(1):16147. doi: [10.1038/s41598-023-43048-3](https://doi.org/10.1038/s41598-023-43048-3). PMID: 37752190; PMCID: PMC10522655.

Shah SA, Deng L, Thorsen J, Pedersen AG, Dion MB, Castro-Mejía JL, Silins R, Romme FO, Sausset R, **Jessen LE**, Ndela EO, Hjelmsø M, Rasmussen MA, Redgwell TA, Leal Rodríguez C, Vestergaard G, Zhang Y, Chawes B, Bønnelykke K, Sørensen SJ, Bisgaard H, Enault F, Stokholm J, Moineau S, Petit MA, Nielsen DS. Expanding known viral diversity in the healthy infant gut. *Nat Microbiol*. 2023 May;8(5):986-998. doi: [10.1038/s41564-023-01345-7](https://doi.org/10.1038/s41564-023-01345-7). Epub 2023 Apr 10. PMID: 37037943; PMCID: PMC10159846.

**Povlsen HR**, Bentzen AK, Kadivar M, **Jessen LE**, Hadrup SR, Nielsen M. Improved T cell receptor antigen pairing through data-driven filtering of sequencing information from single cells. *Elife*. 2023 May 3;12:e81810. doi: [10.7554/eLife.81810](https://doi.org/10.7554/eLife.81810). PMID: 37133356; PMCID: PMC10156162.

### 2022

Skougaard M, **Drachmann C**, Stisen ZR, Ditlev SB, **Jessen LE**, Kristensen LE. OP0103 gene expression profiles retrieved from single cell rna sequencing reveal phenotypic traits in patients with psoriatic arthritis initiating tumour necrosis factor alpha inhibitor and interleukin-17 inhibitor. *Ann Rheum Dis.* 2022;81:68. [10.1136/annrheumdis-2022-eular.3511](http://dx.doi.org/10.1136/annrheumdis-2022-eular.3511)

**Montemurro A**, **Jessen LE**, Nielsen M. NetTCR-2.1: Lessons and guidance on how to develop models for TCR specificity predictions. *Front Immunol*. 2022 Dec 6;13:1055151. doi: [10.3389/fimmu.2022.1055151](https://doi.org/10.3389/fimmu.2022.1055151). PMID: 36561755; PMCID: PMC9763291.

### 2021

Özgümüş T, Sulaieva O, **Jessen LE**, Jain R, Falhammar H, Nyström T, Catrina SB, Jörneskog G, Groop L, Eliasson M, Eliasson B, Brismar K, Stokowy T, Nilsson PM, Lyssenko V. Reduced expression of OXPHOS and DNA damage genes is linked to protection from microvascular complications in long-term type 1 diabetes: the PROLONG study. *Sci Rep*. 2021 Oct 20;11(1):20735. doi: [10.1038/s41598-021-00183-z](https://doi.org/10.1038/s41598-021-00183-z). PMID: 34671071; PMCID: PMC8528906.

**Montemurro A**, Schuster V, **Povlsen HR**, Bentzen AK, Jurtz V, Chronister WD, Crinklaw A, Hadrup SR, Winther O, Peters B, **Jessen LE**, Nielsen M. NetTCR-2.0 enables accurate prediction of TCR-peptide binding by using paired TCRα and β sequence data. *Commun Biol*. 2021 Sep 10;4(1):1060. doi: [10.1038/s42003-021-02610-3](https://doi.org/10.1038/s42003-021-02610-3). PMID: 34508155; PMCID: PMC8433451.

Chronister WD, Crinklaw A, Mahajan S, Vita R, Koşaloğlu-Yalçın Z, Yan Z, Greenbaum JA, **Jessen LE**, Nielsen M, Christley S, Cowell LG, Sette A, Peters B. TCRMatch: Predicting T-Cell Receptor Specificity Based on Sequence Similarity to Previously Characterized Receptors. *Front Immunol*. 2021 Mar 11;12:640725. doi: [10.3389/fimmu.2021.640725](https://doi.org/10.3389/fimmu.2021.640725). PMID: 33777034; PMCID: PMC7991084.

### 2020

Jain R, Özgümüş T, Jensen TM, du Plessis E, Keindl M, Møller CL, Falhammar H, Nyström T, Catrina SB, Jörneskog G, **Jessen LE**, Forsblom C, Haukka JK, Groop PH, Rossing P, Groop L, Eliasson M, Eliasson B, Brismar K, Al-Majdoub M, Nilsson PM, Taskinen MR, Ferrannini E, Spégel P, Berg TJ, Lyssenko V. Liver nucleotide biosynthesis is linked to protection from vascular complications in individuals with long-term type 1 diabetes. *Sci Rep*. 2020 Jul 14;10(1):11561. doi: [10.1038/s41598-020-68130-y](https://doi.org/10.1038/s41598-020-68130-y). PMID: 32665614; PMCID: PMC7360755.

Barra C, Ackaert C, Reynisson B, Schockaert J, **Jessen LE**, Watson M, Jang A, Comtois-Marotte S, Goulet JP, Pattijn S, Paramithiotis E, Nielsen M. Immunopeptidomic Data Integration to Artificial Neural Networks Enhances Protein-Drug Immunogenicity Prediction. *Front Immunol*. 2020 Jun 23;11:1304. doi: [10.3389/fimmu.2020.01304](https://doi.org/10.3389/fimmu.2020.01304). PMID: 32655572; PMCID: PMC7325480.

### 2019

Jensen KK, Rantos V, Jappe EC, Olsen TH, Jespersen MC, Jurtz V, **Jessen LE**, Lanzarotti E, Mahajan S, Peters B, Nielsen M, Marcatili P. TCRpMHCmodels: Structural modelling of TCR-pMHC class I complexes. *Sci Rep*. 2019 Oct 10;9(1):14530. doi: [10.1038/s41598-019-50932-4](https://doi.org/10.1038/s41598-019-50932-4). PMID: 31601838; PMCID: PMC6787230.

Deng L, Silins R, Castro-Mejía JL, Kot W, **Jessen LE**, Thorsen J, Shah S, Stokholm J, Bisgaard H, Moineau S, Nielsen DS. A Protocol for Extraction of Infective Viromes Suitable for Metagenomics Sequencing from Low Volume Fecal Samples. *Viruses*. 2019 Jul 20;11(7):667. doi: [10.3390/v11070667](https://doi.org/10.3390/v11070667). PMID: 31330855; PMCID: PMC6669555.

Bentzen AK, Such L, Jensen KK, Marquard AM, **Jessen LE**, Miller NJ, Church CD, Lyngaa RB, Koelle DM, Becker JC, Linnemann C, Schumacher TNM, Marcatili P, Nghiem P, Nielsen M, Hadrup SR. Dissecting the T cell receptor interactions governing recognition of peptide-MHC complexes. *Eur. J. Immunol*. 2019;49(Suppl. 3 SI):1787-1787. O116.

### 2018

Bentzen AK, Such L, Jensen KK, Marquard AM, **Jessen LE**, Miller NJ, Church CD, Lyngaa R, Koelle DM, Becker JC, Linnemann C, Schumacher TNM, Marcatili P, Nghiem P, Nielsen M, Hadrup SR. T cell receptor fingerprinting enables in-depth characterization of the interactions governing recognition of peptide-MHC complexes. *Nat Biotechnol*. 2018 Nov 19:10.1038/nbt.4303. doi: [10.1038/nbt.4303](https://doi.org/10.1038/nbt.4303). PMID: 30451992; PMCID: PMC9452375.

Wang J, Kurilshikov A, Radjabzadeh D, Turpin W, Croitoru K, Bonder MJ, Jackson MA, Medina-Gomez C, Frost F, Homuth G, Rühlemann M, Hughes D, Kim HN; MiBioGen Consortium Initiative; Spector TD, Bell JT, Steves CJ, Timpson N, Franke A, Wijmenga C, Meyer K, Kacprowski T, Franke L, Paterson AD, Raes J, Kraaij R, Zhernakova A. Meta-analysis of human genome-microbiome association studies: the **MiBioGen consortium initiative**. *Microbiome*. 2018 Jun 8;6(1):101. doi: [10.1186/s40168-018-0479-3](https://doi.org/10.1186/s40168-018-0479-3). PMID: 29880062; PMCID: PMC5992867.

Haworth S, Shungin D, van der Tas JT, Vucic S, Medina-Gomez C, Yakimov V, Feenstra B, Shaffer JR, Lee MK, Standl M, Thiering E, Wang C, Bønnelykke K, Waage J, **Jessen LE**, Nørrisgaard PE, Joro R, Seppälä I, Raitakari O, Dudding T, Grgic O, Ongkosuwito E, Vierola A, Eloranta AM, West NX, Thomas SJ, McNeil DW, Levy SM, Slayton R, Nohr EA, Lehtimäki T, Lakka T, Bisgaard H, Pennell C, Kühnisch J, Marazita ML, Melbye M, Geller F, Rivadeneira F, Wolvius EB, Franks PW, Johansson I, Timpson NJ. Consortium-based genome-wide meta-analysis for childhood dental caries traits. Hum Mol Genet. 2018 Sep 1;27(17):3113-3127. doi: [10.1093/hmg/ddy237](https://doi.org/10.1093/hmg/ddy237). PMID: 29931343; PMCID: PMC6097157.

Waage J, Standl M, Curtin JA, **Jessen LE**, Thorsen J, Tian C, Schoettler N; 23andMe Research Team; AAGC collaborators; Flores C, Abdellaoui A, Ahluwalia TS, Alves AC, Amaral AFS, Antó JM, Arnold A, Barreto-Luis A, Baurecht H, van Beijsterveldt CEM, Bleecker ER, Bonàs-Guarch S, Boomsma DI, Brix S, Bunyavanich S, Burchard EG, Chen Z, Curjuric I, Custovic A, den Dekker HT, Dharmage SC, Dmitrieva J, Duijts L, Ege MJ, Gauderman WJ, Georges M, Gieger C, Gilliland F, Granell R, Gui H, Hansen T, Heinrich J, Henderson J, Hernandez-Pacheco N, Holt P, Imboden M, Jaddoe VWV, Jarvelin MR, Jarvis DL, Jensen KK, Jónsdóttir I, Kabesch M, Kaprio J, Kumar A, Lee YA, Levin AM, Li X, Lorenzo-Diaz F, Melén E, Mercader JM, Meyers DA, Myers R, Nicolae DL, Nohr EA, Palviainen T, Paternoster L, Pennell CE, Pershagen G, Pino-Yanes M, Probst-Hensch NM, Rüschendorf F, Simpson A, Stefansson K, Sunyer J, Sveinbjornsson G, Thiering E, Thompson PJ, Torrent M, Torrents D, Tung JY, Wang CA, Weidinger S, Weiss S, Willemsen G, Williams LK, Ober C, Hinds DA, Ferreira MA, Bisgaard H, Strachan DP, Bønnelykke K. Genome-wide association and HLA fine-mapping studies identify risk loci and genetic pathways underlying allergic rhinitis. *Nat Genet*. 2018 Aug;50(8):1072-1080. doi: [10.1038/s41588-018-0157-1](https://doi.org/10.1038/s41588-018-0157-1). Epub 2018 Jul 16. Erratum in: Nat Genet. 2018 Sep;50(9):1343. PMID: 30013184; PMCID: PMC7068780.

Bønnelykke K, Coleman AT, Evans MD, Thorsen J, Waage J, Vissing NH, Carlsson CJ, Stokholm J, Chawes BL, **Jessen LE**, Fischer TK, Bochkov YA, Ober C, Lemanske RF Jr, Jackson DJ, Gern JE, Bisgaard H. Cadherin-related Family Member 3 Genetics and Rhinovirus C Respiratory Illnesses. Am J Respir Crit Care Med. 2018 Mar 1;197(5):589-594. doi: [10.1164/rccm.201705-1021OC](https://doi.org/10.1164/rccm.201705-1021OC). PMID: 29121479; PMCID: PMC6005238.

Medina-Gomez C, Kemp JP, Trajanoska K, Luan J, Chesi A, Ahluwalia TS, Mook-Kanamori DO, Ham A, Hartwig FP, Evans DS, Joro R, Nedeljkovic I, Zheng HF, Zhu K, Atalay M, Liu CT, Nethander M, Broer L, Porleifsson G, Mullin BH, Handelman SK, Nalls MA, **Jessen LE**, Heppe DHM, Richards JB, Wang C, Chawes B, Schraut KE, Amin N, Wareham N, Karasik D, Van der Velde N, Ikram MA, Zemel BS, Zhou Y, Carlsson CJ, Liu Y, McGuigan FE, Boer CG, Bønnelykke K, Ralston SH, Robbins JA, Walsh JP, Zillikens MC, Langenberg C, Li-Gao R, Williams FMK, Harris TB, Akesson K, Jackson RD, Sigurdsson G, den Heijer M, van der Eerden BCJ, van de Peppel J, Spector TD, Pennell C, Horta BL, Felix JF, Zhao JH, Wilson SG, de Mutsert R, Bisgaard H, Styrkársdóttir U, Jaddoe VW, Orwoll E, Lakka TA, Scott R, Grant SFA, Lorentzon M, van Duijn CM, Wilson JF, Stefansson K, Psaty BM, Kiel DP, Ohlsson C, Ntzani E, van Wijnen AJ, Forgetta V, Ghanbari M, Logan JG, Williams GR, Bassett JHD, Croucher PI, Evangelou E, Uitterlinden AG, Ackert-Bicknell CL, Tobias JH, Evans DM, Rivadeneira F. Life-Course Genome-wide Association Study Meta-analysis of Total Body BMD and Assessment of Age-Specific Effects. *Am J Hum Genet*. 2018 Jan 4;102(1):88-102. doi: [10.1016/j.ajhg.2017.12.005](https://doi.org/10.1016/j.ajhg.2017.12.005). PMID: 29304378; PMCID: PMC5777980.
