---
title: "Team"
---

## Current

- [Leon Eyrich Jessen](https://www.linkedin.com/in/leonjessen/), Head of Lab, Associate Professor (tenured), PhD., MSc. (Eng)
- [Golnaz Rezaee](https://www.linkedin.com/in/golnaz-rezaee-708a09355/), Erasmus+ Research Intern: "Towards ML-Driven Explainable Mapping of T-Cell Receptor Repertoire Signatures in Autoimmune Disease Phenotypes" (October 1st 2025 → March 1st, 2026)
- [William Hagedorn-Rasmussen](https://www.linkedin.com/in/william-hagedorn-rasmussen-51167a264/), Master Thesis student: "Machine Learning-Driven Deconvolution of Superantigen-TCR Interactions in Atopic Dermatitis Using Single-Cell TCRomics" (August 25th 2025 → January 25th 2026) in collaboration with LEO Foundation Skin Immunology Research Center
- [Amanda Jimenez](https://www.linkedin.com/in/amanda-jimenez-43b61224b/), Master Thesis student: "Inferring Functional Gene Networks from Giga-Scale Single-Cell Perturbation Data" (August 25th 2025 → January 25th 2026) in collaboration with Novo Nordisk A/S
- [Sofie Bruun](https://www.linkedin.com/in/sofie-bruun/), Master Thesis student: "Investigating the Impact of DNA Damage on Ribosomal DNA Variation" (September 3rd, 2025 → February 18th 2026) in Collaboration with The Danish Cancer Society
- [John Vinh Quang Tran](https://www.linkedin.com/in/john-vinh-quang-tran-4a0607198/), Master Thesis student: "Identification of important features for capsular contracture using machine learning and network analysis" (September 1st, 2025 → February 1st, 2026) in Collaboration with UCPH Skin Immunology Research Center
- [Sol Escamilla Torres](https://www.linkedin.com/in/sol-escamilla-torres-7199b7235/), Special Course student: "Mapping of Linear Antibody Epitopes Using High-Density Peptide Arrays in Neuroimmunology" (February 2nd, 2026 → May 11th, 2026) in collaboration with Bispebjerg Hospital Neurological Dept.
- [Marcel Skumantz](https://www.linkedin.com/in/marcel-skumantz/), Special Course student: "Computational Drug Discovery and AI-Assisted Molecular Design" (February 1st, 2026 → June 30th, 2026) in Collaboration with DTU BRIGHT and Swaza Life Inc.

## Alumni

### Funded Projects

- [Melanie Randahl Nielsen](https://www.linkedin.com/in/melanie-nielsen-97767a169/) Research Assistant: "Integrative Single-Cell Analysis for Exploring Autoimmune Disease Mechanisms" (09/2023 → 09/2024)
- [Clara Drachmann](https://www.linkedin.com/in/clara-drachmann-5739a7107/) PhD student: "Integrative Single-Cell Analysis for Exploring Autoimmune Disease Mechanisms" (03/2022 → 07/2023)
- [Alessandro Montemurro](https://www.linkedin.com/in/alessandro-montemurro-a41765157/) PhD student: "Improved Immunoinformatic Methods for Rationale T Cell Epitope Discovery" (10/2019 → 01/2023)
- [Helle Rus Povlsen](https://www.linkedin.com/in/helle-povlsen-73b7bb12a/) PhD student: "Development of Immunoinformatics prediction methods for improved rational identification of T cell epitopes" (04/2019 → 12/2022)
- [Anna Lisa Schaap-Johansen](https://www.linkedin.com/in/anna-lisa-schaap-johansen-557994142/) PhD student: "Deep Learning methods for Immunotherapy" (12/2018 → 01/2023)

### Student Projects

- [Jakob Sandfort Ytte](https://www.linkedin.com/in/jakob-sandfort-ytte-980236198/), Bachelor Thesis student: "Graph-Guided PCA Compression for Interpretable Modeling of Childhood Asthma from RNA-seq Data" (September 1st 2025 → December 7th, 2025)
- [Amalie Schultz-Nielsen](https://www.linkedin.com/in/amalie-schultz-nielsen-a0619a241/), Special Course student: "Identification and analysis of T-Cell Receptor Data in Atopic Dermatitis" (February 3, 2025 → May 12, 2025) in collaboration with LEO Foundation Skin Immunology Research Center
- [Emilie Sophie Ragnhild Sonne](), Bachelor Thesis student: "Comparative Analysis of Methods for Clustering of T-cell Receptors" (September 2, 2024 → December 20, 2024)
- [Huiyu Xie](https://www.linkedin.com/in/huiyu-xie-b9b877148/), Master Thesis student: "Applications of Probabilistic Modelling for Profiling Human T-cell Repertoires in Cancer" in collaboration with Department of Molecular Medicine (MOMA), AUH (August 26, 2024 → January 26, 2025)
- [Oscar Lauritz Møberg](https://www.linkedin.com/in/oscar-lauritz-møberg-02a39820a/), Master Thesis student: "Towards Precision Immuno-profiles using Graph Neural Networks for Modelling single cell RNAseq-data" (August 26, 2024 → January 26, 2025) in collaboration with DTU Compute
- [Huiyu Xie](https://www.linkedin.com/in/huiyu-xie-b9b877148/), Special Course student: "Applications of profile Hidden Markov Models for Automated Data Driven QC of T-cell Receptor Sequence Data" (June 6, 2024 → August 23, 2024)
- [Jonathan Dragestad Møller](https://www.linkedin.com/in/jonathan-dragestad-møller-38b51a237/), Special Course student: "Multi-modal analysis of isoforms in cancer" (February 1, 2024 → June 14, 2024)
- [William Hagedorn-Rasmussen](https://www.linkedin.com/in/william-hagedorn-rasmussen-51167a264/), Special Course student: "Applied Biostatistics with Tidy Modelling" (January 29, 2024 → May 31, 2024)
- [Ana Pastor Mediavilla](https://www.linkedin.com/in/anapastorme/), Special Course student: "Multi-modal analysis of isoforms in cancer" (January 29, 2024 → May 19, 2024)
- [Cathrine Lind](https://www.linkedin.com/in/cathrine-lind-066b38193/), Special Course student: "Connecting non-data Literate Stakeholders to Data using R and Shiny: A case study using Cardio Vascular Disease" (September 18, 2023 → November 6, 2023)
- [Bernat Godayol Farran](), Master Thesis student: "Sub-gene level re-analysis of proteomics data" (August 28, 2023 → February 28, 2024)
- [Mikkel Swartz](https://www.linkedin.com/in/mikkel-swartz/), Master Thesis student: "Sub-gene level re-analysis of proteomics data" (August 28, 2023 → January 28, 2024)
- [Signe Marcussen](https://www.linkedin.com/in/signe-marcussen-ba73a6211/), Special Course student: "Characterisation of T-cell Receptors of Malignant T-cells in Cutaneous T-cell Lymphoma" (August 28, 2023 → December 14, 2023) in collaboration with LEO Foundation Skin Immunology Research Center
- [Mathias Nørgaard Stokholm](https://www.linkedin.com/in/mathias-stokholm-2b480b17a/), Master Thesis student: "Integration of longitudinal single-cell RNAseq datasets into a comprehensive reference map to allow automatic annotation of cells generated in stem cell to beta cell protocols." (August 7, 2023 → February 7, 2024) in collaboration with Novo Nordisk A/S
- [Angeliki Kallia Spentza](https://www.linkedin.com/in/angeliki-kallia-spentza/), Special Course student: "Comparative Analysis of Single Cell- and Bulk RNAseq Sequencing Data" (February 24, 2023 → June 22, 2023)
- [Sarah Rosenberg Asmussen](https://www.linkedin.com/in/sarah-rosenberg-asmussen-015895226/), Special Course student: "Using Deep Generative Neural Networks to Model the T-cell Receptor Repertoire" (January 30, 2023 → May 26, 2023) in collaboration with Evaxion Biotech A/S
- [Mathias Grøn Therp](https://www.linkedin.com/in/mathias-gt/), Special Course student: "Mapping Chemicals to Adverse Outcome Pathways" (January 30, 2023 → May 9, 2023) in collaboration with Novo Nordisk Foundation Center for Protein Research
- [Aldis Helga Björgvinsdóttir](), Master Thesis student: "Exploratory Study of Metabolomics and Kidney Function in the UK Biobank Population: Insights from Type 2 Diabetes Stratification" (January 23, 2023 → June 23, 2023) in collaboration with Steno Diabetes Center Copenhagen
- [Melanie Randahl Nielsen](https://www.linkedin.com/in/melanie-nielsen-97767a169/), Master Thesis student: "Machine Learning-Driven Diagnostics for Psoriatic Arthritis Based on Single-Cell Transcriptomics Data" (January 2, 2023 → June 2, 2023)
- [Casper Rasmussen](https://www.linkedin.com/in/casper-rasmussen-738a1a1bb/), Master Thesis student: "Use of L1000 Expression Data to Elucidate Biological Mechanisms" (January 2, 2023 → January 17, 2024) in collaboration with Novo Nordisk A/S
- [Daniel Caleb Romero Yianni](https://www.linkedin.com/in/danielcromero/), Special Course student: "Decoding Metabolic Disease using Single-Cell Technologies, Genomics and Data Science" (September 15, 2022 → February 15, 2023) in collaboration with Novo Nordisk Foundation Center for Basic Metabolic Research
- [William Hagedorn-Rasmussen](https://www.linkedin.com/in/william-hagedorn-rasmussen-51167a264/), Bachelor Thesis student: "Exploring CD8+ T-cell Specificities using Single Cell Immune Profiling with an Outlook to Reproducible Bio Data Science" (August 29, 2022 → January 13, 2023)
- [Alban Laus Obel Slabowska](https://www.linkedin.com/in/alban-obel/), Master Thesis student: "Single-cell deconvolution for spatial-transcriptomics data to extrapollate cell-types on Visium Spatial Gene Expression 10x Genomics technology images" (August 22, 2022 → January 22, 2023) in collaboration with Novo Nordisk A/S
- [Dominik Rafacz](https://www.linkedin.com/in/dominik-rafacz-4592b8164/), Special Course student: "Design and Implementation of Automated Immuno-Sequence Redundancy Handling to Improve Input to Machine Learning Models" (January 31, 2022 → May 9, 2022) in collaboration with Medical University of Bialystok
- [Esben Vestergaard Øyan](https://www.linkedin.com/in/esben-v-1427a4174/), Special Course student: "Applications of Graph Theory in Immuno Research" (January 3, 2022 → January 21, 2022)
- [Christian Holm Johansen](https://www.linkedin.com/in/christian-holm-johansen-202704210/), Special Course student: "Antibody sequence analysis" (August 30, 2021 → December 31, 2021) in collaboration with Novo Nordisk A/S
- [Jacob Korslund Schlander](https://www.linkedin.com/in/jacob-schlander-171b25157/), Bachelor Thesis student: "Exploration of Applications of Graph Theory for Exploring Molecular Level Immunity" (August 30, 2021 → December 3, 2021)
- [Signe Marcussen](https://www.linkedin.com/in/signe-marcussen-ba73a6211/), Bachelor Thesis student: "Application of Machine Learning for mapping TCR::pMHC Specificities using High Throughput Single Cell Immune Profiling Data" (August 30, 2021 → December 3, 2021)
- [Lucille Augusta Green](https://www.linkedin.com/in/lucille-augusta-green-690b231bb/), Bachelor Thesis student: "Application of Machine Learning for mapping TCR::pMHC Specificities using High Throughput Single Cell Immune Profiling Data" (August 30, 2021 → December 3, 2021)
- [Frederik Steensgaard Gade](https://www.linkedin.com/in/fsgade/), Special Course student: "Scientific Writing: Paper on the CrediSite Method" (August 30, 2021 → December 3, 2021)
- [Andreea Teodora Bejenariu](https://www.linkedin.com/in/teodora-and-bejenariu/), Bachelor Thesis student: "Exploration of TCR::pMHC Specificities using High Throughput Single Cell Immune Profiling Data" (February 1, 2021 → July 15, 2021)
- [Frederik Steensgaard Gade](https://www.linkedin.com/in/fsgade/), Bachelor Thesis student: "Bayesian Inference of Amino Acid Level Geno-/Phenotype Correlation in Protein Multiple Sequence Alignments" (February 1, 2021 → June 24, 2021)
- [Sule Altintas](https://www.linkedin.com/in/sulealtintas/), Special Course student: "Post-GWAS Analysis of IL6 Levels" (January 4, 2021 → January 24, 2021) in collaboration with Steno Diabetes Center Copenhagen
- [Laia Meseguer Monfort](https://www.linkedin.com/in/laia-meseguer-monfort-0b6855b4/), Master Thesis student: "Post-GWAS Analysis on Atrial Fibrillation Patients" (August 24, 2020 → January 24, 2021) in collaboration with Department of Biomedical Sciences, UCPH
- [Cecilie Agerlin Møller](https://www.linkedin.com/in/cecilie-møller/), Master Thesis student: "Development of a QSAR model related to endocrine disruption" (August 24, 2020 → January 24, 2021) in collaboration with DTU National Food Institute
- [Frederik Steensgaard Gade](https://www.linkedin.com/in/fsgade/), Special Course student: "Bioinformatics of amino acid level geno-/phenotype correlation" (August 3, 2020 → August 21, 2020)
- [Maarten Marijn van Elst](https://www.linkedin.com/in/maarten-van-elst/), Special Course student: "Exploring Receptor Sequence Diversity of CD4+/CD8+ T-cells" (February 3, 2020 → May 12, 2020)
- [Clara Drachmann](https://www.linkedin.com/in/clara-drachmann-5739a7107/), Special Course student: "Scientific Article Writing: Paper on the NetMHCcons method" (December 6, 2019 → December 6, 2019)
- [Cecilia Bang Jensen](https://www.linkedin.com/in/cecilia-bang-jensen-b81846ba/), Master Thesis student: "Designing a clinical bioinformatics framework for molecular characterization of glioblastoma multiforme" (November 4, 2019 → April 4, 2020)
- [Clara Drachmann](https://www.linkedin.com/in/clara-drachmann-5739a7107/), Bachelor Thesis student: "The Development of a Consensus Method for Improved Prediction of MHC-I Peptide Binding and Antigen Presentation" (February 4, 2019 → June 14, 2019)
- [Søren Steenstrup Zeeberg](https://www.linkedin.com/in/søren-steenstrup-zeeberg-767103251/), Bachelor Thesis student: "Dimensionality Reduction Techniques in Malaria Immunology and Pathogenesis Research" (February 4, 2019 → June 14, 2019)
- [Sebastian Nymann Deleuran](https://www.linkedin.com/in/sebastian-n-deleuran-90252b178/), Bachelor Thesis student: "Integration of RNASeq Expression Data for Improved Prediction of MHC Class I Antigen Presentation " (February 4, 2019 → June 3, 2019)
- [Jakob Hartvig Stiesmark](https://www.linkedin.com/in/jhs/), Bachelor Thesis student: "Large-scale in silico Screening of MHC class II Mediated Immunogenicity of Aero Allergens" (February 4, 2019 → June 3, 2019) in collaboration with COPSAC